//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdOrder { get; set; }
        public int IdTypeOfPayment { get; set; }
        public System.DateTime DateTimeOfPayment { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual TypeOfPayment TypeOfPayment { get; set; }
        public virtual User User { get; set; }
    }
}
