//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warranty
    {
        public int Id { get; set; }
        public int IdOrder { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal Cost { get; set; }
        public string Description { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
